### ISSUE TITLE
FR: clipr integration

### ISSUE THREAD

**Issue by krlmlr** [MilesMcBain/fnmate#1]
Would you support a mode of operation that reads from the clipboard and writes to it?

**Comment by MilesMcBain** [comment]
At the moment the interface takes a character vector of text and a cursor index in that buffer. Based on these it works out what function encloses the cursor.

To use the clipboard would mean, I think, that you can only pass the vector of text. So there's no way to determine the function to define other than to make some assumption: that is the first function called within the clipboard text is probably the most obvious.

What do you think about that UI? In my workflow that would be a bit cumbersome. What text editor are you targetting?

I'm open to the idea if it can be made to work neatly.

**Comment by krlmlr** [comment]
The UI would be:

1. Copy function call to clipboard
2. Invoke RStudio add-in, it puts the function definition on the clipboard
3. Paste function definition to some other location

**Comment by MilesMcBain** [comment]
If it's in RStudio, would it be slightly less friction if 1. was based off cursor pos?

**Comment by MilesMcBain** [comment]
I.e 1. put cursor somewhere on function.

**Comment by krlmlr** [comment]
I guess that would work equally well.

**Comment by MilesMcBain** [comment]
If you're happy with that it can be added very cheaply. 👍

**Comment by MilesMcBain** [comment]
@krlmlr, I've implemented this. Let me know if it suits your workflow!
