### ISSUE TITLE
`rs_fn_defn_jump()` error

### ISSUE THREAD

**Issue by shirdekel** [MilesMcBain/fnmate#13]
Thanks for working on `rs_fn_defn_jump()`! Always seems like you're working on something as soon as I need it. Unfortunately I got the following error when running `rs_fn_defn_jump()` (both in VSCode and RStudio) and I'm not sure how to diagnose. I'm using `ripgrep` 12.1.1.

``` r
fnmate::rs_fn_defn_jump()                                                                                                                                                                                              
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `'rg' -m1 --vimgrep \bget_parameters\s*(?:<-|=)\s*'
NULL
Warning message:
In system2("rg", args = c(other_args, search_regex), stdout = TRUE) :
  running command ''rg' -m1 --vimgrep \bget_parameters\s*(?:<-|=)\s*' had status 2
```

``` r
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin17.0          
 ui       X11                         
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Australia/Sydney            
 date     2021-03-10                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                            
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                    
 cachem        1.0.4      2021-02-13 [1] CRAN (R 4.0.2)                    
 callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.2)                    
 cli           2.3.1      2021-02-23 [1] CRAN (R 4.0.2)                    
 crayon        1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                    
 desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                    
 devtools    * 2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                    
 dflow       * 0.0.0.9000 2020-06-17 [1] Github (milesmcbain/dflow@930b847)
 ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                    
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.0.2)                    
 fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                    
 glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
 jsonlite      1.7.2      2020-12-09 [1] CRAN (R 4.0.2)                    
 lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                    
 magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                    
 memoise       2.0.0      2021-01-26 [1] CRAN (R 4.0.2)                    
 pkgbuild      1.2.0      2020-12-15 [1] CRAN (R 4.0.2)                    
 pkgload       1.2.0      2021-02-23 [1] CRAN (R 4.0.2)                    
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                    
 processx      3.4.5      2020-11-30 [1] CRAN (R 4.0.2)                    
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.0.2)                    
 purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                    
 R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                    
 remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                    
 rlang         0.4.10     2020-12-30 [1] CRAN (R 4.0.2)                    
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.0.2)                    
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                    
 testthat      3.0.2      2021-02-14 [1] CRAN (R 4.0.2)                    
 usethis     * 2.0.1      2021-02-10 [1] CRAN (R 4.0.2)                    
 withr         2.4.1      2021-01-26 [1] CRAN (R 4.0.2)                    

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

**Comment by MilesMcBain** [comment]
Thanks for reporting!

You're on a newer major version of rip grep than I tested with... but with such a simple regex I am skeptical about that being the issue.

Doe the git grep option work? `options(fnmate_searcher = "git_grep")`

**Comment by shirdekel** [comment]
With `options(fnmate_searcher = "git_grep")` it works.

**Comment by shirdekel** [comment]
However, for different function, neither work:

``` r
fnmate::rs_fn_defn_jump()                                                                                                                                                                                              
NULL
Warning message:
In system2("git", args = other_args, stdout = TRUE) :
  running command ''git' grep -nE '\bget_plot\s*(<-|=)\s*' -- \*.R' had status 1
```

``` r
fnmate::rs_fn_defn_jump()                                                                                                                                                                                              
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `'rg' -m1 --vimgrep \bget_plot\s*(?:<-|=)\s*'
NULL
Warning message:
In system2("rg", args = c(other_args, search_regex), stdout = TRUE) :
  running command ''rg' -m1 --vimgrep \bget_plot\s*(?:<-|=)\s*' had status 2
```

**Comment by MilesMcBain** [comment]
Status 1 is what you currently get for a miss - no result found. Is that function within the directory structure or coming from somewhere else?

I've tested your version of rg on my Windows work PC and I don't see the same issue. I am now wondering if it's something to do with `system2` on MacOS, I have never tested this on Mac as I don't own an Apple device.

**Comment by MilesMcBain** [comment]
I should definitely make a nicer message for status 1!

**Comment by shirdekel** [comment]
Re: status 1, jumping to that particular function now works I think because it wasn't tracked by git before (and now I made sure it is). So I guess the error message could also refer to that possibility? That is, that while the file may exist, it needs to tracked. But maybe I'm wrong about this, I don't know enough about `git grep`.

Re: status 2, is there something I can do to help diagnose it further? I'd rather use `rg` if it means that I can still jump to functions I'm not tracking yet.

**Comment by MilesMcBain** [comment]
Yes. See if this works from the command line in your repo dir:

```
rg -m1 --vimgrep '\bget_plot\s*(?:<-|=)\s*'
```

**Comment by shirdekel** [comment]
Running the following seems to work (replaced it with a function I actually have in the repo, `get_plot()` was one I made for the example).

```
rg -m1 --vimgrep '\bget_parameters\s*(?:<-|=)\s*' 
R/get_parameters.R:8:1:get_parameters <- function() {
```

However, ``syntax error near unexpected token `('`` makes me think that the issue may have something to do with my complete file path, which has parentheses (from the uni Dropbox account directory name). I get this error if I just `cd` to an unescaped file path. But I also don't know why that would be relevant if `system2` is just sending to the repo directory.

**Comment by MilesMcBain** [comment]
Oh that's interesting yeah it could be bubbling up from inside 'rg', it's not expecting that parenthesis issue and just bombing.

If you like you could try with 'ag': https://github.com/ggreer/the_silver_searcher

If that works at the command line, I'd be happy to accept a PR that adds it to the possible search tools. The change is not too onerous, just contained to this file: https://github.com/MilesMcBain/fnmate/blob/master/R/jump.R

You can use what's done for `rg` and `git grep` as a guide.

**Comment by shirdekel** [comment]
Unfortunately `ag` behaves similarly to `rg`. That is, working fine in the command line, but getting ``syntax error near unexpected token `('`` with `system2`.

**Comment by shirdekel** [comment]
I figured it out. The regex string needs apostrophes. That is:

``` r
search_regex <- glue::glue("'\\b{fn_name}\\s*(?:<-|=)\\s*'")
```
instead of 

``` r
search_regex <- glue::glue("\\b{fn_name}\\s*(?:<-|=)\\s*")
```

**Comment by shirdekel** [comment]
At the moment, the function is giving `system2` `'rg' -m1 --vimgrep \bripgrep\s*(?:<-|=)\s*`, which is producing the syntax error, whereas `'rg' -m1 --vimgrep '\bripgrep\s*(?:<-|=)\s*'` works.

**Comment by shirdekel** [comment]
I'll submit a PR.

Side note: doesn't seem like you should add `ag` anyway, because it has a weird issue with the `m1` argument. It gives this error: `ERR: Too many matches in ./R/jump.R. Skipping the rest of this file.`, which seems to be an unresolved issue with `ag` (https://github.com/ggreer/the_silver_searcher/issues/483). Although there might be a different argument you could use instead if you really needed to add it here.
