### ISSUE TITLE
Error in locate_fn_target(text, index) 

### ISSUE THREAD

**Issue by matthew-phelps** [MilesMcBain/fnmate#6]
Hi Miles - thanks for all the work you've put into your packages. I'm excited to try `fnmate` in my workflow, but I'm unable to get `fnamte` to function on my setup. I was wondering if you had any insight.

For example, opening a new R session and running `Create function definition file` with the cursor on the following line:

```R
test_fn = function(x)
````

Returns the following:
`Error in locate_fn_target(text, index) : 
  fnmate couldn't find a parsable function at cursor.`

I'm running Rstudio 1.3.959

My session info is:
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Denmark.1252  LC_CTYPE=English_Denmark.1252    LC_MONETARY=English_Denmark.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0    packrat_0.5.0 
```
I've also tried on R 3.6.3. 

This is my first time writing a GitHub issue, so please let me know any improvements I could make
Cheers

**Comment by MilesMcBain** [comment]
Hi @matthew-phelps,

Thanks for trying this out.

The way I intended `fnmate` to work was that you type out the function call and build from that, not the function definition.

So instead of what you've got there, I write:

```
test_fn(x)
```

and call fnmate with the cursor somewhere within the span of those characters. It generates a new file with:

```
##' .. content for \description{} (no empty lines) ..
##'
##' .. content for \details{} ..
##'
##' @title
##' @param x
##' @return
##' @author Miles McBain
##' @export
test_fn <- function(x) {

  NULL

}
```

**Comment by matthew-phelps** [comment]
Hi @MilesMcBain, thanks for your reply

I was still getting the same error after making the changes you suggest above.

I think error arose because I accidentally assigned `Create function definition file` command to `ctrl + alt + F`, which is already assigned to `Run function definition` in RStudio on Windows. 

Removing the custom shortcut fixed the problem.

PS - I'm really enjoying this feature - thanks for making it!
