### ISSUE TITLE
Jump to function using git grep?

### ISSUE THREAD

**Issue by andycraig** [MilesMcBain/fnmate#9]
Hi, thank you for adding the jump to function functionality! It's working nicely for me when I use languageserver on a project that isn't a single package.

I sometimes use systems where I can't install ripgrep but git is available, so I've [written a version for `git grep`](https://github.com/MilesMcBain/fnmate/compare/master...andycraig:jump-gitgrep). I tried GNU Grep first but it spent too much time in `renv`, and excluding directories seems to be a bit of a hassle in older versions of GNU Grep, whereas `git grep` will skip `renv` it's in `.gitignore`.

Is this something you'd be interested in merging into fnmate? If so, I can do a PR. If not (maintainability considerations etc.), no worries :)

**Comment by MilesMcBain** [comment]
Oooh Yes. Sorry I didn't see this until now. I would be very interested in a PR for this!

**Comment by andycraig** [comment]
Great! I'll put together a PR.

**Comment by MilesMcBain** [comment]
I was able to create the PR #10 direct from your link! :)

**Comment by MilesMcBain** [comment]
Looked good to me :)

**Comment by andycraig** [comment]
Wow, can't argue with that efficiency! Thank you! :)
